/** SSS / FAQ content — en, tr, de, es */

const ARCHIVE = '/gecmis';
const HOME = '/';
const SUPPORT = 'mailto:support@woxibulksave.com';

export const SSS_CONTENT = {
  tr: {
    meta: {
      title: 'Sıkça Sorulan Sorular',
      description: 'WBS hakkında sıkça sorulan sorular. Twitter/X toplu video analizi, güvenlik ve kullanım rehberi.',
    },
    page: {
      title: 'Sıkça Sorulan Sorular',
      subtitle: 'WBS kullanımı hakkında merak ettikleriniz.',
      backToHome: '← Ana sayfaya dön',
    },
    items: [
      { question: 'X (Twitter) videoları yüksek kalitede (HD) nasıl analiz edilir?', answer: 'WBS arayüzüne X video linkini yapıştırın; sistemimiz videonun mevcut en yüksek çözünürlüğünü (720p, 1080p vb.) otomatik olarak analiz eder ve size en kaliteli seçeneği sunar.', links: [{ phrase: 'WBS arayüzüne', href: HOME }] },
      { question: 'X videolarını analiz etmek için giriş yapmak zorunda mıyım?', answer: 'Hayır, misafir kullanıcı olarak tek tek 3 gönderi linki analiz edebilirsiniz; çoklu link veya toplu indirme için X kullanıcı girişi gerekir.' },
      { question: 'WBS şifremi veya kişisel verilerimi saklar mı?', answer: 'Kesinlikle hayır. WBS güvencesiyle, X (Twitter) resmi OAuth altyapısı kullanılır; şifreniz asla sistemimize ulaşmaz ve verileriniz Row Level Security (RLS) ile korunur. Sistemimiz X şifrenizi asla talep etmez. Daha fazla analiz yapmak ve analiz arşivinizi saklamak için X kullanıcı girişi yapmanız yeterlidir.' },
      { question: 'Mobil cihazlardan (iPhone/Android) X videosu nasıl analiz edilir?', answer: "Tarayıcınızdan WBS'ye girip linki yapıştırmanız yeterlidir; herhangi bir ek uygulama indirmenize gerek kalmadan videoları doğrudan cihazınıza aktarabilirsiniz.", links: [{ phrase: "WBS'ye girip", href: HOME }] },
      { question: 'Birden fazla linki aynı anda analiz edebilir miyim?', answer: 'Evet, gelişmiş link ayıklama özelliğimiz sayesinde metin içindeki tüm X linklerini otomatik olarak bulup sizin için listeliyoruz.' },
      { question: 'WBS ile hangi videoları analiz edebilirim?', answer: 'Herhangi bir X (Twitter) gönderisindeki videoyu linki yapıştırarak analiz edebilirsiniz; sistemimiz tüm video formatlarını tanır ve size en iyi çözünürlüğü sunar.' },
      { question: 'Neden bazı videoları analiz edemiyorum?', answer: 'X hesabınızın kısıtlı olması veya videonun bulunduğu hesabın "Gizli" (Protected) olması durumunda videoya erişim sağlanamayabilir; bunun dışındaki tüm genel paylaşımlar sorunsuz işlenir.' },
      { question: 'Analiz işlemi ücretli mi?', answer: 'Hayır, WBS temel özellikleri tamamen ücretsiz sunar; misafir haklarınız dolduğunda X kullanıcı girişi yaparak ücretsiz olarak kullanmaya devam edebilirsiniz.' },
      { question: 'Analiz ettiğim videoları nerede bulabilirim?', answer: 'Eğer X kullanıcı girişi yaptıysanız, geçmişte analiz ettiğiniz tüm videolara profilinizdeki "Arşivim" sayfasından dilediğiniz zaman ulaşabilirsiniz.', links: [{ phrase: 'Arşivim', href: ARCHIVE }] },
      { question: "WBS'yi diğer araçlardan ayıran nedir?", answer: 'Biz sadece bir analiz aracı değiliz; WBS güvencesiyle, reklamsız, hızlı ve kullanıcı verisini koruyan profesyonel bir analiz platformuyuz.' },
      { question: 'WBS ile analiz edilen videoların ses kalitesi düşer mi?', answer: 'Hayır, sistemimiz videoyu X sunucularındaki orijinal formatıyla analiz eder; görüntü kalitesiyle birlikte ses bit hızını da (bitrate) koruyarak kayıpsız bir aktarım sağlar.' },
      { question: 'Analiz ettiğim bir videoyu başkaları görebilir mi?', answer: 'Gizliliğiniz bizim önceliğimizdir; yaptığınız bireysel analizler ve geçmişiniz sadece sizin hesabınıza özeldir ve üçüncü taraflarla asla paylaşılmaz.' },
      { question: 'WBS tarayıcı eklentisi olarak çalışıyor mu?', answer: 'Şu an için web tabanlı (SaaS) olarak hizmet veriyoruz; bu sayede cihazınıza hiçbir ek yazılım kurmadan, her yerden güvenle analiz yapabilirsiniz.' },
      { question: 'Videoları toplu olarak analiz etmek mümkün mü?', answer: 'Evet, akıllı link ayıklama özelliğimiz sayesinde yapıştırdığınız metin içerisindeki tüm videoları aynı anda analiz edebilir ve liste halinde yönetebilirsiniz.', links: [{ phrase: 'liste halinde yönetebilirsiniz', href: ARCHIVE }] },
      { question: 'Destek veya geri bildirim için kime ulaşabilirim?', answer: 'Her türlü soru ve öneriniz için WBS destek kanalları üzerinden bizimle iletişime geçebilirsiniz; kullanıcı deneyimini sizin geri bildirimlerinizle geliştirmeye devam ediyoruz.', links: [{ phrase: 'bizimle iletişime geçebilirsiniz', href: SUPPORT }] },
      { question: 'WBS ücretsiz mi kalacak?', answer: 'Temel video analiz özelliklerimiz her zaman ücretsiz kalacaktır; WBS olarak amacımız, dijital araçlara erişimi herkes için kolay ve güvenli hale getirmektir.' },
      { question: 'Analiz ettiğim videoların dosya formatı nedir?', answer: 'Videolar, tüm modern cihazlarla (telefon, tablet, bilgisayar) tam uyumlu olan standart MP4 formatında sunulur; böylece herhangi bir dönüştürücüye ihtiyaç duymazsınız.' },
      { question: 'WBS reklam içeriyor mu?', answer: 'Kullanıcı deneyimini bozmamak adına sistemimizde rahatsız edici pop-up veya aldatıcı reklamlar bulundurmuyoruz; sadece temiz ve işlevsel bir arayüz sunuyoruz.' },
      { question: 'X (Twitter) haricinde diğer platformları destekliyor musunuz?', answer: 'Şu an için odak noktamız X (Twitter) platformudur; uzmanlığımızı bu alanda derinleştirerek size en stabil ve hızlı hizmeti sunmayı amaçlıyoruz.' },
      { question: 'WBS ile canlı yayın videolarını analiz edebilir miyim?', answer: 'Yayın tamamlanıp video haline dönüştüğü andan itibaren tüm içerikleri analiz edebilirsiniz.' },
      { question: 'Analiz edilen videoların kalitesi neden rakiplerden daha yüksek?', answer: 'WBS, videoları sıkıştırmadan, X sunucularındaki orijinal veri akışını (stream) yakalayarak size sunar; bu da görüntü kaybını sıfıra indirir.' },
      { question: 'WBS mobil uygulama olarak yüklenebilir mi?', answer: 'Sitemiz PWA (Progressive Web App) uyumludur; tarayıcınızdan "Ana Ekrana Ekle" diyerek bir uygulama gibi hızlıca erişebilir ve kullanabilirsiniz.' },
      { question: 'Videoları analiz ederken internet kotamı nasıl korurum?', answer: 'Analiz ekranında sunduğumuz farklı çözünürlük seçenekleri (düşük, orta, yüksek) arasından ihtiyacınıza uygun olanı seçerek veri tasarrufu sağlayabilirsiniz.' },
      { question: 'Gizli veya özel profillerdeki videoları analiz edebilir miyim?', answer: 'Hayır. WBS, X (Twitter) kullanıcı gizliliği standartlarına ve platformun güvenlik protokollerine tam uyumlu çalışır. Bu nedenle sadece herkese açık (public) paylaşımları analiz edebilirsiniz. Gizli hesaplara erişim sağlamak ne teknik olarak ne de etik olarak sistemimizde mümkün değildir.' },
      { question: 'iPhone (iOS) cihazlarda video analizi nasıl yapılır?', answer: 'iPhone kullanıcıları için ek bir uygulamaya gerek yoktur. Safari tarayıcısı üzerinden sitemize giriş yapıp, kopyaladığınız video linkini yapıştırmanız yeterlidir. Analiz tamamlandığında "Analiz Et" butonuna basarak videoyu doğrudan "Dosyalar" uygulamanıza veya fotoğraf galerinize aktarabilirsiniz. (Not: iOS 13 ve üzeri sürümler en akıcı deneyimi sunar.)', links: [{ phrase: 'sitemize giriş yapıp', href: HOME }] },
      { question: 'WBS kullanımında herhangi bir analiz sınırı var mı?', answer: 'Temel kullanımda herhangi bir sayı sınırı bulunmamaktadır. Ancak, sistem sağlığını ve her kullanıcının aynı yüksek hızı almasını garanti etmek amacıyla, art arda yapılan işlemler arasında kısa bir "stabilizasyon süresi" beklenebilir.' },
      { question: 'Android telefonlarda sistem nasıl çalışıyor?', answer: 'Android cihazlarda işlem oldukça pratiktir. X uygulamasından aldığınız video bağlantısını WBS giriş alanına yapıştırıp "Analiz Et" demeniz yeterlidir. Sistemimiz videoyu saniyeler içinde işler ve cihazınıza en yüksek kalitede saklamanıza olanak tanır.', links: [{ phrase: 'WBS giriş alanına', href: HOME }] },
      { question: 'Videolar hangi formatta hazırlanıyor ve canlı yayınları destekliyor mu?', answer: 'Tüm videolar, evrensel uyumluluğu en yüksek olan MP4 formatında sunulur. Ayrıca, X platformunda tamamlanmış ve arşive düşmüş canlı yayın içeriklerini de WBS ile analiz edebilir ve yüksek çözünürlüklü olarak saklayabilirsiniz.' },
      { question: 'Analiz ettiğim dosyaları cihazımda nerede bulabilirim?', answer: 'Analiz edilen içerikler, cihazınızın varsayılan "İndirilenler" (Downloads) klasörüne aktarılır. Bilgisayarlarda tarayıcı geçmişinden (CTRL+J), mobil cihazlarda ise dosya yöneticisi uygulaması üzerinden bu içeriklere anında ulaşabilirsiniz.' },
      { question: 'İçerik kullanımı ve telif hakları konusunda nelere dikkat etmeliyim?', answer: 'WBS bir içerik analiz ve erişim aracıdır. Arşivinizdeki içeriklerin fikri mülkiyet hakları paylaşım yapan kullanıcıya veya ilgili platforma aittir. İçerikleri sadece kişisel arşiv, akademik araştırma veya gazetecilik gibi yasal sınırlar dahilinde kullanmanız gerektiğini hatırlatırız.' },
    ],
  },
  en: {
    meta: {
      title: 'Frequently Asked Questions',
      description: 'WBS FAQ — bulk Twitter/X video analysis, security, and how to use the tool.',
    },
    page: {
      title: 'Frequently Asked Questions',
      subtitle: 'Everything you need to know about using WBS.',
      backToHome: '← Back to home',
    },
    items: [
      { question: 'How do I analyze X (Twitter) videos in HD quality?', answer: 'Paste the X video link into the WBS interface; our system automatically analyzes the highest available resolution (720p, 1080p, etc.) and presents the best option.', links: [{ phrase: 'WBS interface', href: HOME }] },
      { question: 'Do I need to sign in to analyze X videos?', answer: 'No — as a guest you can analyze 3 post links one at a time. Multiple links or bulk download require signing in with your X account.' },
      { question: 'Does WBS store my password or personal data?', answer: 'Absolutely not. WBS uses the official X (Twitter) OAuth flow; your password never reaches our servers and your data is protected with Row Level Security (RLS). We never ask for your X password. Sign in with your X account to analyze more and save to your archive.' },
      { question: 'How do I analyze X videos on mobile (iPhone/Android)?', answer: 'Open WBS in your browser and paste the link — no extra app required. You can save videos directly to your device.', links: [{ phrase: 'Open WBS', href: HOME }] },
      { question: 'Can I analyze multiple links at once?', answer: 'Yes. Our smart link extraction finds all X links in pasted text and lists them for you automatically.' },
      { question: 'What videos can I analyze with WBS?', answer: 'Any video in a public X (Twitter) post — paste the link and our system recognizes all common video formats and offers the best resolution.' },
      { question: 'Why can’t I analyze some videos?', answer: 'If your X account is restricted or the post is from a protected (private) account, access may fail. All other public posts are processed normally.' },
      { question: 'Is analysis paid?', answer: 'No. WBS core features are free. When guest limits are reached, sign in with your X account to continue for free.' },
      { question: 'Where can I find videos I analyzed?', answer: 'If you signed in with your X account, open My Archive anytime to see your full analysis history.', links: [{ phrase: 'My Archive', href: ARCHIVE }] },
      { question: 'What makes WBS different from other tools?', answer: 'We are not just a downloader — WBS is a fast, ad-free platform built to protect your data and deliver professional bulk analysis.' },
      { question: 'Does WBS reduce audio quality?', answer: 'No. We analyze from X servers in the original format, preserving video and audio bitrate for lossless transfer.' },
      { question: 'Can others see videos I analyzed?', answer: 'Your privacy comes first. Individual analyses and history belong only to your account and are never shared with third parties.' },
      { question: 'Does WBS work as a browser extension?', answer: 'We currently offer a web-based (SaaS) service — analyze securely from anywhere without installing extra software.' },
      { question: 'Can I analyze videos in bulk?', answer: 'Yes. Paste text containing multiple links and our extractor analyzes all videos at once; you can manage them in a list.', links: [{ phrase: 'manage them in a list', href: ARCHIVE }] },
      { question: 'Who can I contact for support or feedback?', answer: 'Reach us through WBS support channels for any question or suggestion — we improve the product with your feedback.', links: [{ phrase: 'Reach us', href: SUPPORT }] },
      { question: 'Will WBS stay free?', answer: 'Core video analysis will always be free. WBS aims to make digital tools accessible and secure for everyone.' },
      { question: 'What file format are analyzed videos?', answer: 'Videos are delivered in standard MP4, compatible with phones, tablets, and computers — no converter needed.' },
      { question: 'Does WBS show ads?', answer: 'We avoid intrusive pop-ups and misleading ads. You get a clean, focused interface.' },
      { question: 'Do you support platforms other than X (Twitter)?', answer: 'Our focus is X (Twitter) for now — we deepen expertise there to give you the most stable, fastest service.' },
      { question: 'Can I analyze live stream recordings with WBS?', answer: 'Once a broadcast ends and is saved as a video on X, you can analyze it like any other post.' },
      { question: 'Why is WBS video quality often higher than competitors?', answer: 'WBS captures the original stream from X servers without extra compression, minimizing quality loss.' },
      { question: 'Can I install WBS as a mobile app?', answer: 'Our site is PWA-ready. Use “Add to Home Screen” in your browser for app-like quick access.' },
      { question: 'How can I save mobile data when analyzing?', answer: 'Choose lower, medium, or high resolution on the analysis screen to match your data needs.' },
      { question: 'Can I analyze videos from private or protected profiles?', answer: 'No. WBS complies with X privacy and security rules. Only public posts can be analyzed — private accounts are neither technically nor ethically accessible.' },
      { question: 'How does video analysis work on iPhone (iOS)?', answer: 'No extra app needed. Open our site in Safari, paste the video link, and tap Analyze. Save to Files or Photos when done. (iOS 13+ recommended.)', links: [{ phrase: 'Open our site', href: HOME }] },
      { question: 'Is there a limit on how many videos I can analyze?', answer: 'There is no fixed cap for normal use. To keep the system fast for everyone, brief stabilization delays may apply between rapid consecutive requests.' },
      { question: 'How does WBS work on Android?', answer: 'Copy the video link from the X app, paste it into the WBS input field, and tap Analyze. Results are ready in seconds at the highest available quality.', links: [{ phrase: 'WBS input field', href: HOME }] },
      { question: 'What format are videos and do you support live streams?', answer: 'All videos are MP4 for broad compatibility. Completed live streams archived on X can also be analyzed and saved in high resolution with WBS.' },
      { question: 'Where are analyzed files saved on my device?', answer: 'Files go to your default Downloads folder. On desktop use the browser downloads panel (Ctrl+J); on mobile use your file manager.' },
      { question: 'What should I know about copyright and content use?', answer: 'WBS is an analysis and access tool. Rights belong to the poster or platform. Use content only within legal limits such as personal archive, research, or journalism.' },
    ],
  },
  de: {
    meta: {
      title: 'Häufig gestellte Fragen',
      description: 'WBS FAQ — Massenanalyse von Twitter/X-Videos, Sicherheit und Bedienung.',
    },
    page: {
      title: 'Häufig gestellte Fragen',
      subtitle: 'Alles Wichtige zur Nutzung von WBS.',
      backToHome: '← Zur Startseite',
    },
    items: [
      { question: 'Wie analysiere ich X (Twitter)-Videos in HD-Qualität?', answer: 'Fügen Sie den X-Video-Link in die WBS-Oberfläche ein; unser System analysiert automatisch die höchste verfügbare Auflösung (720p, 1080p usw.) und bietet die beste Option.', links: [{ phrase: 'WBS-Oberfläche', href: HOME }] },
      { question: 'Muss ich mich anmelden, um X-Videos zu analysieren?', answer: 'Nein — als Gast können Sie 3 Beitragslinks analysieren. Für mehr Analysen und Ihren Verlauf empfehlen wir die Anmeldung mit Ihrem X-Konto.' },
      { question: 'Speichert WBS mein Passwort oder persönliche Daten?', answer: 'Nein. WBS nutzt offizielles X (Twitter) OAuth; Ihr Passwort erreicht unsere Server nie, Daten werden per Row Level Security (RLS) geschützt. Wir fragen nie nach Ihrem X-Passwort.' },
      { question: 'Wie analysiere ich X-Videos auf dem Handy (iPhone/Android)?', answer: 'Öffnen Sie WBS im Browser und fügen Sie den Link ein — keine Extra-App nötig.', links: [{ phrase: 'Öffnen Sie WBS', href: HOME }] },
      { question: 'Kann ich mehrere Links gleichzeitig analysieren?', answer: 'Ja. Unsere Link-Erkennung findet alle X-Links im eingefügten Text und listet sie automatisch.' },
      { question: 'Welche Videos kann ich mit WBS analysieren?', answer: 'Jedes Video in einem öffentlichen X (Twitter)-Beitrag — Link einfügen, System erkennt gängige Formate und bietet die beste Auflösung.' },
      { question: 'Warum kann ich manche Videos nicht analysieren?', answer: 'Bei eingeschränkten Konten oder geschützten (privaten) Profilen kann der Zugriff fehlschlagen. Öffentliche Beiträge funktionieren normal.' },
      { question: 'Ist die Analyse kostenpflichtig?', answer: 'Nein. WBS-Kernfunktionen sind kostenlos. Nach Gast-Limits einfach mit X-Konto anmelden.' },
      { question: 'Wo finde ich analysierte Videos?', answer: 'Mit X-Anmeldung finden Sie Ihren gesamten Verlauf unter Mein Archiv.', links: [{ phrase: 'Mein Archiv', href: ARCHIVE }] },
      { question: 'Was unterscheidet WBS von anderen Tools?', answer: 'WBS ist eine schnelle, werbefreie Plattform für professionelle Massenanalyse mit Fokus auf Datenschutz.' },
      { question: 'Verschlechtert WBS die Audioqualität?', answer: 'Nein. Analyse erfolgt im Originalformat von X-Servern mit erhaltener Video- und Audio-Bitrate.' },
      { question: 'Können andere meine Analysen sehen?', answer: 'Ihre Analysen und Ihr Verlauf gehören nur Ihrem Konto und werden nicht an Dritte weitergegeben.' },
      { question: 'Gibt es WBS als Browser-Erweiterung?', answer: 'Aktuell als Web-Dienst (SaaS) — ohne Zusatzsoftware von überall nutzbar.' },
      { question: 'Sind Massenanalysen möglich?', answer: 'Ja. Mehrere Links im Text werden erkannt und gleichzeitig analysiert; Verwaltung als Liste möglich.', links: [{ phrase: 'Verwaltung als Liste', href: ARCHIVE }] },
      { question: 'An wen wende ich mich für Support oder Feedback?', answer: 'Kontaktieren Sie uns über die WBS-Supportkanäle — Ihr Feedback verbessert das Produkt.', links: [{ phrase: 'Kontaktieren Sie uns', href: SUPPORT }] },
      { question: 'Bleibt WBS kostenlos?', answer: 'Grundlegende Videoanalyse bleibt kostenlos. WBS soll digitale Tools für alle zugänglich machen.' },
      { question: 'In welchem Format liegen die Videos vor?', answer: 'Standard-MP4, kompatibel mit Telefon, Tablet und PC — kein Konverter nötig.' },
      { question: 'Enthält WBS Werbung?', answer: 'Keine störenden Pop-ups oder irreführende Anzeigen — klare, funktionale Oberfläche.' },
      { question: 'Unterstützen Sie andere Plattformen als X (Twitter)?', answer: 'Derzeit liegt der Fokus auf X (Twitter) für maximale Stabilität und Geschwindigkeit.' },
      { question: 'Kann ich Livestream-Aufzeichnungen analysieren?', answer: 'Sobald die Übertragung beendet und als Video auf X gespeichert ist, wie jeder andere Beitrag analysierbar.' },
      { question: 'Warum ist die WBS-Qualität oft höher?', answer: 'WBS nutzt den Originalstream von X ohne zusätzliche Kompression.' },
      { question: 'Kann ich WBS als App installieren?', answer: 'PWA-fähig — „Zum Home-Bildschirm“ im Browser für schnellen Zugriff.' },
      { question: 'Wie spare ich mobiles Datenvolumen?', answer: 'Wählen Sie auf dem Analysebildschirm niedrige, mittlere oder hohe Auflösung.' },
      { question: 'Gehen private oder geschützte Profile?', answer: 'Nein. Nur öffentliche Beiträge — gemäß X-Datenschutz und Sicherheitsregeln.' },
      { question: 'Videoanalyse auf iPhone (iOS)?', answer: 'Safari öffnen, Link einfügen, Analysieren tippen, in Dateien oder Fotos speichern. (iOS 13+ empfohlen.)', links: [{ phrase: 'Safari öffnen', href: HOME }] },
      { question: 'Gibt es Analyse-Limits?', answer: 'Kein festes Limit im Normalbetrieb. Kurze Pausen zwischen vielen schnellen Anfragen können der Systemstabilität dienen.' },
      { question: 'Wie funktioniert WBS auf Android?', answer: 'Link aus der X-App kopieren, in das WBS-Eingabefeld einfügen, Analysieren — Ergebnis in Sekunden.', links: [{ phrase: 'WBS-Eingabefeld', href: HOME }] },
      { question: 'Format und Livestreams?', answer: 'MP4 für breite Kompatibilität. Abgeschlossene Livestreams auf X können in hoher Auflösung analysiert werden.' },
      { question: 'Wo finde ich Dateien auf dem Gerät?', answer: 'Im Standard-Download-Ordner; am PC über Browser-Downloads (Strg+J), mobil über den Dateimanager.' },
      { question: 'Urheberrecht und Nutzung?', answer: 'WBS ist ein Analyse- und Zugriffstool. Rechte liegen beim Ersteller oder der Plattform. Nur legale Nutzung (privates Archiv, Forschung, Journalismus).' },
    ],
  },
  es: {
    meta: {
      title: 'Preguntas frecuentes',
      description: 'FAQ de WBS — análisis masivo de vídeos de Twitter/X, seguridad y uso.',
    },
    page: {
      title: 'Preguntas frecuentes',
      subtitle: 'Todo lo que necesita saber sobre WBS.',
      backToHome: '← Volver al inicio',
    },
    items: [
      { question: 'Cómo analizo vídeos de X (Twitter) en calidad HD?', answer: 'Pegue el enlace del vídeo en la interfaz de WBS; el sistema analiza automáticamente la resolución más alta disponible (720p, 1080p, etc.).', links: [{ phrase: 'interfaz de WBS', href: HOME }] },
      { question: 'Debo iniciar sesión para analizar vídeos de X?', answer: 'No — como invitado puede analizar 3 enlaces de publicaciones. Para más análisis y su historial, inicie sesión con su cuenta de X.' },
      { question: 'WBS guarda mi contraseña o datos personales?', answer: 'No. WBS usa OAuth oficial de X (Twitter); su contraseña nunca llega a nuestros servidores y los datos están protegidos con Row Level Security (RLS).' },
      { question: 'Cómo analizo vídeos en móvil (iPhone/Android)?', answer: 'Abra WBS en el navegador y pegue el enlace — sin aplicación extra.', links: [{ phrase: 'Abra WBS', href: HOME }] },
      { question: 'Puedo analizar varios enlaces a la vez?', answer: 'Sí. Nuestra extracción inteligente encuentra todos los enlaces de X en el texto pegado.' },
      { question: 'Qué vídeos puedo analizar con WBS?', answer: 'Cualquier vídeo en una publicación pública de X (Twitter); el sistema reconoce formatos habituales y ofrece la mejor resolución.' },
      { question: 'Por qué no puedo analizar algunos vídeos?', answer: 'Si la cuenta está restringida o el perfil es privado, el acceso puede fallar. Las publicaciones públicas se procesan con normalidad.' },
      { question: 'El análisis es de pago?', answer: 'No. Las funciones básicas de WBS son gratuitas. Tras el límite de invitado, inicie sesión con X para continuar gratis.' },
      { question: 'Dónde encuentro los vídeos analizados?', answer: 'Con sesión de X, abra Mi archivo para ver todo su historial de análisis.', links: [{ phrase: 'Mi archivo', href: ARCHIVE }] },
      { question: 'Qué diferencia a WBS de otras herramientas?', answer: 'WBS es una plataforma rápida, sin anuncios, centrada en el análisis masivo profesional y la protección de datos.' },
      { question: 'WBS reduce la calidad de audio?', answer: 'No. Analizamos desde los servidores de X en formato original, preservando vídeo y audio.' },
      { question: 'Otros pueden ver mis análisis?', answer: 'Su privacidad es prioritaria. Análisis e historial son solo de su cuenta y no se comparten con terceros.' },
      { question: 'WBS funciona como extensión del navegador?', answer: 'Por ahora ofrecemos un servicio web (SaaS) — sin software adicional.' },
      { question: 'Puedo analizar vídeos en masa?', answer: 'Sí. Pegue texto con varios enlaces; el extractor los analiza a la vez y puede gestionarlos en lista.', links: [{ phrase: 'gestionarlos en lista', href: ARCHIVE }] },
      { question: 'A quién contacto para soporte o comentarios?', answer: 'Escríbanos por los canales de soporte de WBS; mejoramos con sus comentarios.', links: [{ phrase: 'Escríbanos', href: SUPPORT }] },
      { question: 'WBS seguirá siendo gratuito?', answer: 'El análisis básico de vídeo seguirá siendo gratuito. WBS busca herramientas digitales accesibles y seguras para todos.' },
      { question: 'En qué formato están los vídeos?', answer: 'MP4 estándar, compatible con teléfono, tableta y ordenador.' },
      { question: 'WBS tiene publicidad?', answer: 'Sin ventanas emergentes intrusivas ni anuncios engañosos — interfaz limpia.' },
      { question: 'Soportan otras plataformas además de X (Twitter)?', answer: 'Por ahora el foco es X (Twitter) para ofrecer el servicio más estable y rápido.' },
      { question: 'Puedo analizar grabaciones de directos?', answer: 'Cuando la emisión termina y queda guardada como vídeo en X, puede analizarla como cualquier otra publicación.' },
      { question: 'Por qué la calidad de WBS suele ser mayor?', answer: 'WBS captura el flujo original de los servidores de X sin compresión extra.' },
      { question: 'Puedo instalar WBS como app?', answer: 'Compatible con PWA — «Añadir a pantalla de inicio» en el navegador.' },
      { question: 'Cómo ahorro datos móviles?', answer: 'Elija resolución baja, media o alta en la pantalla de análisis.' },
      { question: 'Perfiles privados o protegidos?', answer: 'No. Solo publicaciones públicas, conforme a las normas de privacidad de X.' },
      { question: 'Análisis en iPhone (iOS)?', answer: 'Abra el sitio en Safari, pegue el enlace, pulse Analizar y guarde en Archivos o Fotos. (iOS 13+ recomendado.)', links: [{ phrase: 'Abra el sitio', href: HOME }] },
      { question: 'Hay límite de análisis?', answer: 'Sin límite fijo en uso normal. Pueden aplicarse breves pausas entre muchas solicitudes seguidas.' },
      { question: 'Cómo funciona en Android?', answer: 'Copie el enlace de la app X, péguelo en el campo de WBS y pulse Analizar.', links: [{ phrase: 'campo de WBS', href: HOME }] },
      { question: 'Formato y directos?', answer: 'MP4 para amplia compatibilidad. Directos finalizados archivados en X también se pueden analizar en alta resolución.' },
      { question: 'Dónde están los archivos en el dispositivo?', answer: 'En la carpeta Descargas predeterminada; en PC con el panel de descargas del navegador (Ctrl+J).' },
      { question: 'Derechos de autor y uso del contenido?', answer: 'WBS es una herramienta de análisis y acceso. Los derechos pertenecen al autor o la plataforma. Use el contenido solo dentro de límites legales.' },
    ],
  },
};

export function getSssContent(lang) {
  const key = lang && SSS_CONTENT[lang] ? lang : 'en';
  return SSS_CONTENT[key];
}
